owl_invoice:
    resources:
        invoice:
            classes:
                model: Owl\Component\Core\Model\Invoice\Invoice
                interface: Owl\Component\Core\Model\Invoice\InvoiceInterface
                repository: Owl\Bundle\CoreBundle\Doctrine\ORM\InvoiceRepository
        invoice_tax_rate:
            classes:
                repository: Owl\Bundle\CoreBundle\Doctrine\ORM\InvoiceTaxRateRepository
