owl_invoice:
    resources:
        invoice:
            classes:
                model: Owl\Component\Core\Model\Invoice\Invoice
                interface: Owl\Component\Core\Model\Invoice\InvoiceInterface
        invoice_buyer:
            classes:
                model: Owl\Component\Core\Model\Invoice\Buyer
                interface: Owl\Component\Core\Model\Invoice\BuyerInterface
