owl_invoice:
    resources:
        invoice:
            classes:
                model: Owl\Component\Core\Model\Invoice\Invoice
                interface: Owl\Component\Core\Model\Invoice\InvoiceInterface
