sylius_grid:
    grids:
        owl_admin_company:
            driver:
                name: doctrine/orm
                options:
                    class: "%owl.model.company.class%"
            fields:
                name:
                    type: string
                    label: owl.ui.name
                    sortable: ~
                taxNumber:
                    type: string
                    label: owl.company.tax_number
                    sortable: ~
                address:
                    type: twig
                    label: owl.ui.address
                    path: .
                    options:
                        template: "@OwlAdmin/shared/grid/field/address.html.twig"
                city:
                    type: string
                    label: owl.ui.city
                    sortable: ~
                email:
                    type: string
                    label: owl.ui.email
                    sortable: ~
            filters:
                search:
                    type: string
                    label: owl.ui.search
                    options:
                        fields: [name, nip, city, street, postCode, phone, email]
            actions:
                main:
                    create:
                        type: modal
                        label: owl.ui.create
                        options:
                            button: primary
                            icon: flowbite:plus-outline
                            modal:
                                size: 'default'
                            link:
                                route: owl_admin_company_create
                item:
                    update:
                        type: modal
                        options:
                            tooltip: owl.ui.edit
                            icon: flowbite:pen-solid
                            modal:
                                size: 'default'
                            link:
                                route: owl_admin_company_update
                                parameters:
                                    id: resource.id
                    delete:
                        type: delete
