sylius_grid:
    grids:
        owl_admin_invoice:
            driver:
                name: doctrine/orm
                options:
                    class: "%owl.model.invoice.class%"
            sorting:
                fullNumber: desc
            fields:
                fullNumber:
                    type: string
                    label: owl.ui.full_number
                    sortable: sequenceNumber
                issueDate:
                    type: datetime
                    label: owl.invoice.issue_date
                    sortable: ~
                    options:
                        format: d-m-Y
                contractor:
                    type: string
                    label: owl.ui.contractor
                    path: buyer.company
                    sortable: buyer.company
            filters:
                fullNumber:
                    type: string
                    label: owl.ui.number
            actions:
                main:
                    create:
                        type: create
                item:
                    delete:
                        type: delete
