sylius_grid:
    grids:
        owl_admin_invoice:
            driver:
                name: doctrine/orm
                options:
                    class: "%owl.model.invoice.class%"
            sorting:
                issueDate: desc
            fields:
                fullNumber:
                    type: string
                    label: owl.ui.full_number
                    sortable: sequenceNumber
                issueDate:
                    type: datetime
                    label: owl.invoice.issue_date
                    sortable: ~
                    options:
                        format: d-m-Y
                company:
                    type: string
                    label: owl.ui.company
                    path: company.name
                    sortable: company.name
                contractor:
                    type: string
                    label: owl.ui.contractor
                    path: buyer.company
                    sortable: buyer.company
                subtotal:
                    type: twig
                    label: owl.ui.invoice.net_total
                    path: .
                    options:
                        template: "@OwlAdmin/shared/grid/field/money.html.twig"
                        vars:
                            th_class: "text-end"
                            td_class: "text-end"
                            field: subtotal
                total:
                    type: twig
                    label: owl.ui.invoice.gross_total
                    path: .
                    options:
                        template: "@OwlAdmin/shared/grid/field/money.html.twig"
                        vars:
                            th_class: "text-end"
                            td_class: "text-end"
                            field: total
                is_paid:
                    type: twig
                    label: owl.ui.invoice.payment_status
                    options:
                        template: "@OwlAdmin/invoice/grid/field/paid.html.twig"
            filters:
                fullNumber:
                    type: string
                    label: owl.ui.full_number
                issueDate:
                    type: period
                    options:
                        custom: true
                        saved: true
                company:
                    type: ux_autocomplete
                    label: owl.ui.company
                    form_options:
                        multiple: false
                        placeholder: owl.ui.select_company
                        extra_options:
                            class: '%owl.model.company.class%'
                            choice_label: name
                        attr:
                            'data-controller': 'grid-filter-autocomplete'
                            'data-grid-filter-autocomplete-form-live-name-value': 'owl_admin:invoice:grid_filters:form'
                            'data-grid-filter-autocomplete-field-value': 'company'
                            'data-model': 'norender|criteria[company]'
                    options:
                        fields: [company.id]
                        custom: true
                        saved: true
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete
                bulk:
                    delete:
                        type: delete
