sylius_grid:
    grids:
        owl_admin_locale:
            driver:
                name: doctrine/orm
                options:
                    class: "%owl.model.locale.class%"
            sorting:
                code: asc
            fields:
                name:
                    type: twig
                    label: owl.ui.name
                    path: .
                    sortable: code
                    options:
                        template: "@OwlAdmin/locale/grid/field/name.html.twig"
                code:
                    type: twig
                    label: owl.ui.code
                    sortable: ~
                    options:
                        template: "@OwlAdmin/shared/grid/field/code.html.twig"
            filters:
                code:
                    type: string
                    label: owl.ui.code
            actions:
                main:
                    create:
                        type: modal
                        label: owl.ui.create
                        options:
                            button: primary
                            icon: flowbite:plus-outline
                            modal:
                                size: 'sm'
                            link:
                                route: owl_admin_locale_create
                item:
                    delete:
                        type: delete
