owl_admin_invoice:
    resource: |
        alias: owl.invoice
        section: admin
        path: invoices
        templates: "@OwlAdmin\\shared\\crud"
        except: ['show', 'create']
        redirect: index
        grid: owl_admin_invoice
        form:
            type: Owl\Bundle\AdminBundle\Form\Type\InvoiceType
        permission: true
        vars:
            all:
                redirect:
                    optional_referer: owl_admin_invoice_index
            index:
                referer: true
                permission:
                    group: invoice
                    description: owl.ui.permission.list_invoices
            update:
                form:
                    ajax: true
                permission:
                    group: invoice
                    description: owl.ui.permission.update_invoice
            delete:
                permission:
                    group: invoice
                    description: owl.ui.permission.delete_invoice
            bulkDelete:
                redirect:
                    header: xhr
                form:
                    ajax: true
                permission:
                    group: invoice
                    description: owl.ui.permission.bulk_delete_invoice
    type: sylius.resource

owl_admin_invoice_create:
    path: /invoices/new
    methods: [GET,POST]
    defaults:
        _controller: owl.controller.invoice::createAction
        _sylius:
            section: admin
            permission: true
            template: "@OwlAdmin/shared/crud/create.html.twig"
            form:
                type: Owl\Bundle\AdminBundle\Form\Type\InvoiceType
            factory:
                method: createWithDefaults
                arguments:
                    - !php/const Owl\Component\Invoice\Enum\InvoiceTypeEnum::TYPE_SALES
            vars:
                serialization_groups: [AjaxShow]
                form:
                    ajax: true
                tinymce: true
                permission:
                    group: invoice
                    description: owl.ui.permission.create_invoice

owl_admin_invoice_available_series:
    path: /available-series/{type}
    methods: [GET]
    defaults:
        _controller: owl_admin.controller.invoice.available_series
        _sylius:
            permission: true
            vars:
                permission:
                    group: invoice_serie
                    description: owl.ui.permission.available_invoice_series