# fos_elastica:
#     messenger:
#         enabled: true
#     clients:
#         default: 
#           hosts: ['%env(resolve:OWL_ELASTICSEARCH_HOST)%']
#           username: '%env(resolve:OWL_ELASTICSEARCH_USER)%'
#           password: '%env(resolve:OWL_ELASTICSEARCH_PASSWORD)%'
#           ssl_verification: true
#           ssl_ca: '%env(resolve:OWL_ELASTICSEARCH_SSL_CA_PATH)%'
#     indexes:
#         user:
#             persistence:
#                 # the driver can be orm, mongodb or phpcr
#                 driver: orm
#                 model: "%owl.model.admin_user.class%"
#                 provider: ~
#                 finder: ~
#                 provider:
#                     query_builder_method: listElasticsearch
#             properties:
#                 username: {
#                     type: text,
#                     fields : {
#                         keyword : {
#                             type : keyword,
#                         }
#                     }
#                 }
#                 email: {
#                     type: text,
#                     fields : {
#                         keyword : {
#                             type : keyword,
#                         }
#                     }
#                 }
#                 firstName: {
#                     type: text,
#                     fields : {
#                         keyword : {
#                             type : keyword,
#                         }
#                     }
#                 }
#                 lastName: {
#                     type: text,
#                     fields : {
#                         keyword : {
#                             type : keyword,
#                         }
#                     }
#                 }
#                 displayName: {
#                     type: text,
#                     fields : {
#                         keyword : {
#                             type : keyword,
#                         }
#                     }
#                 }
#                 note: {
#                     type: text,
#                     fields : {
#                         keyword : {
#                             type : keyword,
#                         }
#                     }
#                 }
#                 enabled: {
#                     type: boolean
#                 }
#                 createdAt: {
#                     type: date,
#                     fields : {
#                         keyword : {
#                             type : date,
#                         }
#                     }
#                 }
#                 role_id: {
#                     property_path: role.name,
#                     type: text,
#                     fields : {
#                         keyword : {
#                             type : keyword,
#                         }
#                     }
#                 }
#                 role:
#                     type: "nested"
#                     properties:
#                         name: {
#                             type: text,
#                             fields : {
#                                 keyword : {
#                                     type : keyword,
#                                 }
#                             }
#                         }
#                         setting:
#                             type: "nested"
#                             properties:
#                                 displayName: {
#                                     type: text,
#                                     fields : {
#                                         keyword : {
#                                             type : keyword,
#                                         }
#                                     }
#                                 }
