webpack_encore:
    output_path: '%kernel.project_dir%/public/build/default'
    builds:
        admin: '%kernel.project_dir%/public/build/admin'
        app.admin: '%kernel.project_dir%/public/build/app/admin'
