owl_admin_suggestion_status_history_status:
    path: /history
    methods: [GET]
    defaults:
        _controller: owl.controller.suggestion_status::indexAction
        _sylius:
            section: admin
            permission: true
            template: "@OwlAdmin/suggestion/status/history.html.twig"
            repository:
                method: createHistoryListQueryBuilder
                arguments: 
                    id: $suggestionId
            parents:
                - 
                    resource: owl.suggestion
                    repository: 
                        method: find
                        arguments: 
                            id: $suggestionId
            vars:
                subheader: owl.ui.manage_suggestions
                icon: list
                permission:
                    group: suggestion
                    description: owl.ui.permission.history_status_suggestion

owl_admin_suggestion_status_change_status:
    path: /change-status
    methods: [GET,POST]
    defaults:
        _controller: owl.controller.suggestion_status::createAction
        _sylius:
            section: admin
            permission: true
            template: "@OwlAdmin/shared/crud/modal/create.html.twig"
            factory:
                method: createForSubjectWithOwner
                arguments:
                    - suggestion
                    - "expr:service('owl.context.admin_user').getUser()"
            parents:
                - 
                    resource: owl.suggestion
                    repository: 
                        method: find
                        arguments: 
                            id: $suggestionId
            vars:
                route:
                    name: owl_admin_suggestion_status_change_status
                    parameters: 
                        suggestionId: $suggestionId
                form:
                    ajax: true
                serialization_groups: [AjaxShow]
                permission:
                    group: suggestion
                    description: owl.ui.permission.change_status_suggestion