sylius_grid:
    grids:
        owl_admin_invoice_serie:
            driver:
                name: doctrine/orm
                options:
                    class: "%owl.model.invoice_serie.class%"
            sorting:
                isDefault: desc
            fields:
                format:
                    type: twig
                    label: owl.ui.format
                    sortable: ~
                    options:
                        template: "@OwlAdmin/invoice/serie/grid/format.html.twig"
                invoiceType:
                    type: string
                    label: owl.ui.type
                    sortable: ~
                sequenceIncrement:
                    type: twig
                    label: owl.invoice.sequence_increment
                    sortable: ~
                    options:
                        template: "@OwlAdmin/invoice/serie/grid/sequence_increment.html.twig"
                isDefault:
                    type: twig
                    label: owl.invoice.is_default_serie
                    sortable: ~
                    options:
                        template: "@OwlAdmin/shared/grid/field/boolean.html.twig"
            filters:
                format:
                    type: string
                    label: owl.ui.format
            actions:
                main:
                    create:
                        type: modal
                        label: owl.ui.create
                        options:
                            button: primary
                            icon: flowbite:plus-outline
                            modal:
                                size: 'default'
                            link:
                                route: owl_admin_invoice_serie_create
                item:
                    update:
                        type: modal
                        options:
                            tooltip: owl.ui.edit
                            icon: flowbite:pen-solid
                            modal:
                                size: 'default'
                            link:
                                route: owl_admin_invoice_serie_update
                                parameters:
                                    id: resource.id
                    delete:
                        type: delete
