Owl\Component\Rbac\Model\AuthItem:
    exclusion_policy: NONE
    xml_root_name: rbac_auth_item
    discriminator:
        field_name: type
        map:
            permission: Owl\Component\Rbac\Model\Permission
            role: Owl\Component\Core\Model\Rbac\Role
            # because we extend by Owl\Component\Core\Model\Rbac\Role
            role_base: Owl\Component\Rbac\Model\Role
