sylius_twig_hooks:
    hooks:
        'owl_admin.suggestion.modal.create':
            content:
                template: '@OwlAdmin/shared/crud/common/modal/content.html.twig'
                configuration:
                    stimulus:
                        controllers: {
                            form: {
                                values: {
                                    'async-events': ['upload']
                                }
                            }
                        }
                priority: 0

        'owl_admin.suggestion.modal.create.content.body':
            form:
                template: '@OwlAdmin/shared/crud/common/modal/content/body/form.html.twig'
                priority: 100
            uploader:
                template: '@OwlAdmin/shared/uploader.html.twig'
                configuration:
                    action: form:upload@window->uploader#afterSaveFormEvent
                    replace: 'id'
                    path:
                        route: 'owl_admin_suggestion_file_create'
                        params:
                            suggestionId: 'replaceParamId'
                priority: 0

        'owl_admin.suggestion.modal.create.content.body.form':
            content:
                component: 'owl_admin:suggestion:form'
                props:
                    resource: '@=_context.resource'
                    form: '@=_context.form'
                    template: '@OwlAdmin/suggestion/form.html.twig'
                configuration:
                    method: 'POST'
                priority: 0

        'owl_admin.suggestion.modal.create.content.actions':
            save:
                template: '@OwlAdmin/shared/crud/common/modal/content/actions/save.html.twig'
                configuration:
                    params:
                        save_action: 'save'
                priority: 0


