Owl\Component\Contractor\Model\Contractor:
    exclusion_policy: ALL
    xml_root_name: contractor
    properties:
        id:
            expose: true
            type: integer
            xml_attribute: true
            groups: [AjaxShow]
        companyName:
            expose: true
            type: string
            xml_attribute: true
            groups: [AjaxShow]
