sylius_twig_hooks:
    hooks:
        'owl_admin.common.show':
            sidebar:
                template: '@OwlAdmin/shared/crud/common/sidebar.html.twig'
                priority: 200
            navbar:
                template: '@OwlAdmin/shared/crud/common/navbar.html.twig'
                priority: 100
            content:
                template: '@OwlAdmin/shared/crud/common/content.html.twig'
                priority: 0

        'owl_admin.common.show.content':
            flashes:
                template: '@OwlAdmin/shared/crud/common/content/flashes.html.twig'
                priority: 200
            header:
                template: '@OwlAdmin/shared/crud/common/content/header.html.twig'
                priority: 100
            footer:
                template: '@OwlAdmin/shared/crud/common/content/footer.html.twig'
                priority: -100

        'owl_admin.common.show.content.header':
            breadcrumbs:
                template: '@OwlAdmin/shared/crud/show/content/header/breadcrumbs.html.twig'
                priority: 100
            title_block:
                template: '@OwlAdmin/shared/crud/common/content/header/title_block.html.twig'
                priority: 0

        'owl_admin.common.show.content.header.title_block':
            title:
                template: '@OwlAdmin/shared/crud/show/content/header/title_block/title.html.twig'
                priority: 0
