sylius_twig_hooks:
    hooks:
        'owl_admin.notification.modal.create':
            content:
                template: '@OwlAdmin/shared/crud/common/modal/content.html.twig'
                configuration:
                    stimulus:
                        controllers: {
                            form: {
                                values: {
                                    'async-events': ['upload']
                                }
                            }
                        }
                priority: 0

        'owl_admin.notification.modal.create.content.body':
            form:
                template: '@OwlAdmin/shared/crud/common/modal/content/body/form.html.twig'
                priority: 0
            uploader:
                template: '@OwlAdmin/shared/uploader.html.twig'
                configuration:
                    path:
                        route: 'owl_admin_notification_file_create'
                        params:
                            notificationId: 'replaceParamId'
                priority: 0

        'owl_admin.notification.modal.create.content.body.form':
            content:
                component: 'owl_admin:notification:form'
                props:
                    resource: '@=_context.resource'
                    form: '@=_context.form'
                    template: '@OwlAdmin/notification/modal/form.html.twig'
                configuration:
                    method: 'POST'
                priority: 0

        'owl_admin.notification.modal.create.content.body.uploader':
            content:
                template: '@OwlAdmin/shared/uploader/content.html.twig'
                priority: 0

