sylius_twig_hooks:
    hooks:
        'owl_admin.notification.update#modals':
            delete:
                template: '@OwlAdmin/shared/crud/modal/delete.html.twig'
                priority: 0

        'owl_admin.notification.update':
            content:
                template: '@OwlAdmin/shared/crud/common/content.html.twig'
                configuration:
                    stimulus:
                        controllers: {
                            form: {
                                values: {
                                    'async-events': ['upload']
                                }
                            }
                        }
                priority: 100

        'owl_admin.notification.update.content.body':
            form:
                component: 'owl_admin:notification:form'
                props:
                    resource: '@=_context.resource'
                    form: '@=_context.form'
                    template: '@OwlAdmin/shared/crud/common/content/body/form.html.twig'
                configuration:
                    render_rest: false
                priority: 0

        'owl_admin.notification.update.content.body.form':
            sections:
                template: '@OwlAdmin/notification/form/sections.html.twig'
                priority: 0

        'owl_admin.notification.update.content.body.form.sections#left':
            general:
                template: '@OwlAdmin/notification/form/sections/general.html.twig'
                priority: 0

        'owl_admin.notification.update.content.body.form.sections#right':
            uploader:
                template: '@OwlAdmin/notification/form/sections/uploader.html.twig'
                priority: 0
            files:
                template: '@OwlAdmin/notification/form/sections/files.html.twig'
                priority: 0

        'owl_admin.notification.update.content.body.form.sections.general':
            form:
                template: '@OwlAdmin/notification/form/sections/general/form.html.twig'
                priority: 0

        'owl_admin.notification.update.content.body.form.sections.uploader':
            uploader:
                template: '@OwlAdmin/shared/uploader.html.twig'
                configuration:
                    action: form:upload@window->uploader#afterSaveFormEvent
                    replace: 'id'
                    path:
                        route: 'owl_admin_notification_file_create'
                        params:
                            notificationId: '@=_context.resource.getId()'
                priority: 0

        'owl_admin.notification.update.content.body.form.sections.files':
            files:
                template: '@OwlAdmin/shared/file/list.html.twig'
                configuration:
                    path: 'owl_admin_notification_file_delete'
                priority: 0

        'owl_admin.notification.update.content.header':
            breadcrumbs:
                template: '@OwlAdmin/shared/crud/update/content/header/breadcrumbs.html.twig'
                configuration:
                    rendered_field: subject
                priority: 0