sylius_twig_hooks:
    hooks:
        'owl_admin.invoice.create':
            content:
                template: '@OwlAdmin/shared/crud/common/content.html.twig'
                configuration:
                    stimulus:
                        controllers: {
                            form: {},
                            invoice-form: {
                                outlets: {
                                    'modal': '.owl-modal' 
                                }
                            }
                        }
                priority: 0
        'owl_admin.invoice.create.content':
            header:
                template: '@OwlAdmin/shared/crud/common/content/header.html.twig'
                configuration:
                    full_width: true
                priority: 400
            body:
                template: '@OwlAdmin/shared/crud/common/content/body.html.twig'
                configuration:
                    full_width: true
                    page_body_attributes:
                        'data-form-target': 'content'
                priority: 200

        'owl_admin.invoice.create.content.body':
            form:
                enabled: false
            sections:
                template: '@OwlAdmin/invoice/body/sections.html.twig'
                priority: 0

        'owl_admin.invoice.create.content.body.sections':
            header:
                template: '@OwlAdmin/invoice/body/sections/header.html.twig'
                priority: 100
            form:
                component: 'owl_admin:invoice:form'
                props:
                    resource: '@=_context.resource'
                    form: '@=_context.form'
                    type: '@=_context.resource.getType()'
                    template: '@OwlAdmin/invoice/body/sections/form.html.twig'
                configuration:
                    render_rest: false
                priority: 0

        'owl_admin.invoice.create.content.body.sections.form':
            sections:
                template: '@OwlAdmin/invoice/form/sections.html.twig'
                priority: 0

        'owl_admin.invoice.create.content.body.sections.form.sections':
            default:
                template: '@OwlAdmin/invoice/form/sections/general/default.html.twig'
                priority: 0
