sylius_twig_hooks:
    hooks:
        'owl_admin.invoice.update':
            content:
                template: '@OwlAdmin/shared/crud/common/content.html.twig'
                configuration:
                    page_wrapper_class: 'owl-admin-invoice-form'
                    stimulus:
                        controllers: {
                            form: {},
                            invoice-form: {
                                outlets: {
                                    'modal': '.owl-modal'
                                }
                            }
                        }
                priority: 0

        'owl_admin.invoice.update.content':
            header:
                template: '@OwlAdmin/shared/crud/common/content/header.html.twig'
                configuration:
                    full_width: true
                priority: 400
            body:
                template: '@OwlAdmin/shared/crud/common/content/body.html.twig'
                configuration:
                    full_width: true
                    page_body_attributes:
                        'data-form-target': 'content'
                priority: 200

        'owl_admin.invoice.update.content.body':
            form:
                component: 'owl_admin:invoice:form'
                props:
                    resource: '@=_context.resource'
                    form: '@=_context.form'
                    type: '@=_context.resource.getType()'
                    showPaymentDate: '@=_context.resource.isPaid()'
                    exchangeRateCurrency: '@=_context.resource.getExchangeRateSnapshot()?.getCode()'
                    template: '@OwlAdmin/invoice/form.html.twig'
                configuration:
                    render_rest: false
                priority: 0

        'owl_admin.invoice.update.content.body.form':
            header:
                template: '@OwlAdmin/invoice/form/header.html.twig'
                priority: 100
            sections:
                template: '@OwlAdmin/invoice/form/sections.html.twig'
                priority: 0


        'owl_admin.invoice.update.content.body.form.sections':
            general:
                template: '@OwlAdmin/invoice/form/sections/general.html.twig'
                priority: 300
            payment:
                template: '@OwlAdmin/invoice/form/sections/payment.html.twig'
                priority: 200
            line_items:
                template: '@OwlAdmin/invoice/form/sections/line_items.html.twig'
                priority: 100
            summary:
                template: '@OwlAdmin/invoice/form/sections/summary.html.twig'
                priority: 0