<?php

return [
    Symfony\Bundle\FrameworkBundle\FrameworkBundle::class => ['all' => true],
    Symfony\Bundle\MonologBundle\MonologBundle::class => ['all' => true],
    Symfony\Bundle\TwigBundle\TwigBundle::class => ['all' => true],
    Symfony\Bundle\SecurityBundle\SecurityBundle::class => ['all' => true],
    Doctrine\Bundle\DoctrineBundle\DoctrineBundle::class => ['all' => true],
    Doctrine\Bundle\MigrationsBundle\DoctrineMigrationsBundle::class => ['all' => true],
    JMS\SerializerBundle\JMSSerializerBundle::class => ['all' => true],
    FOS\RestBundle\FOSRestBundle::class => ['all' => true],
    BabDev\PagerfantaBundle\BabDevPagerfantaBundle::class => ['all' => true],
    Sylius\Bundle\MoneyBundle\SyliusMoneyBundle::class => ['all' => true],
    Owl\Bundle\UserBundle\OwlUserBundle::class => ['all' => true],
    Owl\Bundle\ResourceBundle\ResourceBundle::class => ['all' => true],
    Owl\Bundle\CoreBundle\OwlCoreBundle::class => ['all' => true],
    Owl\Bundle\LocaleBundle\OwlLocaleBundle::class => ['all' => true],
    Owl\Bundle\SuggestionBundle\OwlSuggestionBundle::class => ['all' => true],
    Owl\Bundle\NotificationBundle\OwlNotificationBundle::class => ['all' => true],
    Owl\Bundle\CategoryBundle\OwlCategoryBundle::class => ['all' => true],
    Owl\Bundle\StatusBundle\OwlStatusBundle::class => ['all' => true],
    Owl\Bundle\FileBundle\OwlFileBundle::class => ['all' => true],
    Owl\Bundle\RbacBundle\OwlRbacBundle::class => ['all' => true],
    Owl\Bundle\InvoiceBundle\OwlInvoiceBundle::class => ['all' => true],
    Owl\Bundle\LocationBundle\OwlLocationBundle::class => ['all' => true],
    Owl\Bundle\ContractorBundle\OwlContractorBundle::class => ['all' => true],
    Sylius\Bundle\CurrencyBundle\SyliusCurrencyBundle::class => ['all' => true],
    Sylius\Bundle\ResourceBundle\SyliusResourceBundle::class => ['all' => true],
    Sylius\Bundle\GridBundle\SyliusGridBundle::class => ['all' => true],
    Sylius\Bundle\MailerBundle\SyliusMailerBundle::class => ['all' => true],
    Owl\Bundle\UiBundle\OwlUiBundle::class => ['all' => true],
    Owl\Bundle\SettingBundle\OwlSettingBundle::class => ['all' => true],
    Knp\Bundle\GaufretteBundle\KnpGaufretteBundle::class => ['all' => true],
    Sylius\Bundle\ThemeBundle\SyliusThemeBundle::class => ['all' => true],
    Owl\Bundle\AdminBundle\OwlAdminBundle::class => ['all' => true],
    winzou\Bundle\StateMachineBundle\winzouStateMachineBundle::class => ['all' => true],
    Knp\Bundle\MenuBundle\KnpMenuBundle::class => ['all' => true],
    Stof\DoctrineExtensionsBundle\StofDoctrineExtensionsBundle::class => ['all' => true],
    SyliusLabs\DoctrineMigrationsExtraBundle\SyliusLabsDoctrineMigrationsExtraBundle::class => ['all' => true],
    Sylius\Bundle\FixturesBundle\SyliusFixturesBundle::class => ['all' => true],
    FriendsOfBehat\SymfonyExtension\Bundle\FriendsOfBehatSymfonyExtensionBundle::class => ['test' => true, 'test_cached' => true],
    Owl\Bundle\ApiBundle\OwlApiBundle::class => ['all' => true],
    Lexik\Bundle\JWTAuthenticationBundle\LexikJWTAuthenticationBundle::class => ['all' => true],
    Symfony\Bundle\DebugBundle\DebugBundle::class => ['dev' => true],
    Symfony\Bundle\WebProfilerBundle\WebProfilerBundle::class => ['dev' => true, 'test' => true, 'test_cached' => true],
    ApiPlatform\Symfony\Bundle\ApiPlatformBundle::class => ['all' => true],
    Owl\Bundle\TinymceBundle\TinymceBundle::class => ['all' => true],
    Owl\Bundle\GridBundle\OwlGridBundle::class => ['all' => true],
    Symfony\UX\Autocomplete\AutocompleteBundle::class => ['all' => true],
    Symfony\UX\TwigComponent\TwigComponentBundle::class => ['all' => true],
    Symfony\UX\StimulusBundle\StimulusBundle::class => ['all' => true],
    Symfony\UX\LiveComponent\LiveComponentBundle::class => ['all' => true],
    Sylius\TwigHooks\SyliusTwigHooksBundle::class => ['all' => true],
    Symfony\WebpackEncoreBundle\WebpackEncoreBundle::class => ['all' => true],
    Twig\Extra\TwigExtraBundle\TwigExtraBundle::class => ['all' => true],
    Sylius\TwigExtra\Symfony\SyliusTwigExtraBundle::class => ['all' => true],
    Symfony\UX\Icons\UXIconsBundle::class => ['all' => true],
];
