owl_admin_live_component:
    path: '/{_locale}/_components/{_live_component}/{_live_action}'
    defaults:
        _live_action: 'get'

owl_admin_live_component_public:
    path: '/{_locale}/_components_public/{_live_component}/{_live_action}'
    defaults:
        _live_action: 'get'

owl_admin_ux:
    resource: "@OwlAdminBundle/Resources/config/routing/ux.yml"

owl_admin_partial:
    resource: "@OwlAdminBundle/Resources/config/routing/partial.yml"
    prefix: /_partial

owl_admin_dashboard:
    path: /dashboard
    defaults:
        _controller: owl_admin.controller.dashboard::indexAction

owl_admin_profile:
    resource: "@OwlAdminBundle/Resources/config/routing/profile.yml"

owl_admin_suggestion:
    resource: "@OwlAdminBundle/Resources/config/routing/suggestion.yml"

owl_admin_notification:
    resource: "@OwlAdminBundle/Resources/config/routing/notification.yml"

owl_admin_locale:
    resource: "@OwlAdminBundle/Resources/config/routing/locale.yml"

owl_admin_permission:
    resource: "@OwlAdminBundle/Resources/config/routing/rbac.yml"
    prefix: /rbac/

owl_admin_admin_user:
    resource: "@OwlAdminBundle/Resources/config/routing/admin_user.yml"

owl_admin_setting:
    resource: "@OwlAdminBundle/Resources/config/routing/setting.yml"

owl_admin_invoice:
    resource: "@OwlAdminBundle/Resources/config/routing/invoice.yml"

owl_admin_invoice_serie:
    resource: "@OwlAdminBundle/Resources/config/routing/invoice/serie.yml"
    prefix: /invoices/

owl_admin_invoice_tax_rate:
    resource: "@OwlAdminBundle/Resources/config/routing/invoice/tax_rate.yml"
    prefix: /invoices/

owl_admin_contractor:
    resource: "@OwlAdminBundle/Resources/config/routing/contractor.yml"

owl_admin_company:
    resource: "@OwlAdminBundle/Resources/config/routing/company.yml"

owl_admin_country:
    resource: "@OwlAdminBundle/Resources/config/routing/country.yml"

owl_admin_zone:
    resource: "@OwlAdminBundle/Resources/config/routing/zone.yml"

owl_admin_currency:
    resource: "@OwlAdminBundle/Resources/config/routing/currency.yml"

owl_admin_exchange_rate:
    resource: "@OwlAdminBundle/Resources/config/routing/exchange_rate.yml"

owl_admin_security:
    resource: "@OwlAdminBundle/Resources/config/routing/security.yml"