sylius_twig_hooks:
    hooks:
        'owl_admin.suggestion_status.modal.create.content.body':
            form:
                component: 'owl_admin:suggestion_status:form'
                props:
                    resource: '@=_context.resource'
                    form: '@=_context.form'
                    template: '@OwlAdmin/shared/crud/common/content/body/form.html.twig'
                configuration:
                    render_rest: false
                priority: 0

        'owl_admin.suggestion_status.modal.create.content.body.form':
            general:
                template: '@OwlAdmin/suggestion/status/form.html.twig'
                priority: 0

        'owl_admin.suggestion_status.modal.create.content.header.title_block':
            title:
                template: '@OwlAdmin/shared/crud/common/modal/content/header/title_block/title.html.twig'
                configuration:
                    title: 'owl.ui.change_status_suggestion'
                    icon: 'flowbite:arrows-repeat-count-outline'
                priority: 100

        'owl_admin.suggestion_status.modal.create.content.actions':
            save:
                template: '@OwlAdmin/shared/crud/common/modal/content/actions/save.html.twig'
                props:
                configuration:
                    path:
                        route: 'owl_admin_suggestion_status_change_status'
                        params:
                            suggestionId: '@=_context.configuration.getRequest().attributes.get("suggestionId")'
                    method: 
                        name: 'POST'
                    params:
                        save_action: 'referer'
                priority: 0
