sylius_twig_hooks:
    hooks:
        'owl_admin.suggestion_status.modal.history':
            content:
                template: '@OwlAdmin/shared/crud/common/modal/content.html.twig'
                priority: 0

        'owl_admin.suggestion_status.modal.history.content':
            header:
                template: '@OwlAdmin/shared/crud/common/modal/content/header.html.twig'
                priority: 200
            body:
                template: '@OwlAdmin/shared/crud/common/modal/content/body.html.twig'
                priority: 100
            actions:
                template: '@OwlAdmin/shared/crud/common/modal/content/actions.html.twig'
                priority: 0

        'owl_admin.suggestion_status.modal.history.content.header':
            title_block:
                template: '@OwlAdmin/shared/crud/common/modal/content/header/title_block.html.twig'
                priority: 0

        'owl_admin.suggestion_status.modal.history.content.header.title_block':
            title:
                template: '@OwlAdmin/shared/crud/common/modal/content/header/title_block/title.html.twig'
                configuration:
                    title: 'owl.ui.history_suggestion_status'
                    icon: 'flowbite:list-outline'
                priority: 0

        'owl_admin.suggestion_status.modal.history.content.body':
            list:
                template: '@OwlAdmin/suggestion/status/history/list.html.twig'
                priority: 0

        'owl_admin.suggestion_status.modal.history.content.actions':
            cancel:
                template: '@OwlAdmin/shared/crud/common/modal/content/actions/cancel.html.twig'
                priority: 0
