sylius_twig_hooks:
    hooks:
        'owl_admin.exchange_rate.modal.update.content.body':
            form:
                component: 'owl_admin:exchange_rate:form'
                props:
                    resource: '@=_context.resource'
                    form: '@=_context.form'
                    template: '@OwlAdmin/shared/crud/common/modal/content/body/form.html.twig'
                configuration:
                    render_rest: true
                priority: 0
