sylius_mailer:
    sender:
        name: System
        address: '%owl.mail_sender%'
    sender_adapter: sylius.email_sender.adapter.symfony_mailer
    emails:
        admin_password_reset:
            subject: owl.emails.user.password_reset.subject
            template: "@OwlCore/Email/passwordReset.html.twig"
        admin_user_registration:
            subject: owl.emails.user_registration.subject
            template: "@OwlCore/Email/userRegistration.html.twig"
        verification_token:
            subject: owl.emails.user.verification_token.subject
            template: "@OwlCore/Email/verification.html.twig"
        admin_user_registration_accepted:
            subject: owl.emails.user.registration_accepted.subject
            template: "@OwlCore/Email/registrationAccepted.html.twig"
        admin_user_registration_rejected:
            subject: owl.emails.user.registration_rejected.subject
            template: "@OwlCore/Email/registrationRejected.html.twig"
