sylius_twig_hooks:
    hooks:
        'owl_admin.rbac_role.modal.update.content.body':
            form:
                component: 'owl_admin:admin_rbac_role:form'
                props:
                    resource: '@=_context.resource'
                    form: '@=_context.form'
                    template: '@OwlAdmin/shared/crud/common/content/body/form.html.twig'
                configuration:
                    render_rest: false
                priority: 0

        'owl_admin.rbac_role.modal.update.content.body.form':
            sections:
                enabled: false
            general:
                template: '@OwlAdmin/rbac/role/form.html.twig'
                priority: 0