sylius_twig_hooks:
    hooks:
        'owl_admin.security.reset_password':
            page:
                template: '@OwlAdmin/security/common/page.html.twig'
                priority: 0

        'owl_admin.security.reset_password.page':
            logo:
                template: '@OwlAdmin/security/common/logo.html.twig'
                priority: 100
            content:
                template: '@OwlAdmin/security/common/content.html.twig'
                priority: 0

        'owl_admin.security.reset_password.page.logo':
            image:
                template: '@OwlAdmin/security/common/logo/image.html.twig'
                priority: 0

        'owl_admin.security.reset_password.page.content':
            form:
                template: '@OwlAdmin/security/reset_password/page/content/form.html.twig'
                priority: 0

        'owl_admin.security.reset_password.page.content.form':
            password:
                template: '@OwlAdmin/security/reset_password/page/content/form/password.html.twig'
                priority: 100
            submit:
                template: '@OwlAdmin/security/reset_password/page/content/form/submit.html.twig'
                priority: 0
