owl_admin_rbac_role:
    resource: |
        alias: owl.rbac_role
        path: /
        section: admin
        templates: "@OwlAdmin\\shared\\crud"
        except: ['show', 'create', 'update']
        grid: owl_admin_rbac_role
        permission: true
        vars:
            all:
                templates:
                    form: "@OwlAdmin/Rbac/Role/_form.html.twig"
            index:
                referer: true
                permission:
                    group: rbac_permission_role
                    description: owl.ui.permission.list_roles
            delete:
                redirect:
                    header: xhr
                permission:
                    group: rbac_permission_role
                    description: owl.ui.permission.delete_role
    type: sylius.resource

owl_admin_rbac_role_create:
    path: /new
    methods: [GET,POST]
    defaults:
        _controller: owl.controller.rbac_role::createAction
        _sylius:
            section: admin
            permission: true
            template: "@OwlAdmin/shared/crud/modal/create.html.twig"
            vars:
                serialization_groups: [AjaxShow]
                form:
                    ajax: true
                permission:
                    group: rbac_permission_role
                    description: owl.ui.permission.create_role

owl_admin_rbac_role_update:
    path: /{id}/update
    methods: [GET,PUT]
    defaults:
        _controller: owl.controller.rbac_role::updateAction
        _sylius:
            section: admin
            permission: true
            template: "@OwlAdmin/shared/crud/modal/update.html.twig"
            vars:
                serialization_groups: [AjaxShow]
                form:
                    ajax: true
                permission:
                    group: rbac_permission_role
                    description: owl.ui.permission.update_role

owl_admin_rbac_role_permissions:
    path: /{id}/permissions
    methods: [GET]
    defaults:
        _controller: owl.controller.rbac_role::availablesAction
        _sylius:
            section: admin
            permission: true
            # grid: owl_admin_service
            template: "@OwlAdmin/rbac/role/permissions.html.twig"
            form: Owl\Bundle\RbacBundle\Form\Type\AssignType
            vars:
                permission:
                    group: rbac_permission_role
                    description: owl.ui.permissions

owl_admin_rbac_role_assign:
    path: /{id}/assign
    methods: [POST]
    defaults:
        _controller: owl.controller.rbac_role::assignAction
        _format: json
        _sylius:
            serialization_groups: [ADD]
            form: Owl\Bundle\RbacBundle\Form\Type\AssignType
            section: admin
            permission: true
            vars:
                route:
                    parameters:
                        id: $id
                form:
                  ajax: true
                permission:
                    group: rbac_permission_role
                    description: owl.ui.permission.add_permission_to_role

owl_admin_rbac_role_revoke:
    path: /{id}/revoke
    methods: [DELETE]
    defaults:
        _controller: owl.controller.rbac_role::revokeAction
        _format: json
        _sylius:
            serialization_groups: [DELETE]
            form: Owl\Bundle\RbacBundle\Form\Type\AssignType
            section: admin
            permission: true
            vars:
                route:
                    parameters:
                        id: $id
                form:
                  ajax: true
                permission:
                    group: rbac_permission_role
                    description: owl.ui.permission.revoke_permission_to_role
