sylius_twig_hooks:
    hooks:
        'owl_admin.common.modal.create':
            content:
                template: '@OwlAdmin/shared/crud/common/modal/content.html.twig'
                configuration:
                    controller: ['form']
                priority: 0

        'owl_admin.common.modal.create.content':
            header:
                template: '@OwlAdmin/shared/crud/common/modal/content/header.html.twig'
                priority: 200
            body:
                template: '@OwlAdmin/shared/crud/common/modal/content/body.html.twig'
                priority: 100
            actions:
                template: '@OwlAdmin/shared/crud/common/modal/content/actions.html.twig'
                priority: 0

        'owl_admin.common.modal.create.content.body':
            form:
                template: '@OwlAdmin/shared/crud/common/modal/content/body/form.html.twig'
                priority: 0
            loading:
                template: '@OwlAdmin/shared/crud/common/modal/content/body/loading.html.twig'
                priority: 0

        'owl_admin.common.modal.create.content.header':
            title_block:
                template: '@OwlAdmin/shared/crud/common/modal/content/header/title_block.html.twig'
                priority: 0

        'owl_admin.common.modal.create.content.header.title_block':
            title:
                template: '@OwlAdmin/shared/crud/common/modal/content/header/title_block/title.html.twig'
                priority: 0

        'owl_admin.common.modal.create.content.body.form':
            content:
                template: '@OwlAdmin/shared/crud/common/modal/content/body/form/content.html.twig'
                configuration:
                    render_rest: true
                priority: 0

        'owl_admin.common.modal.create.content.body.form.content':
            sections:
                template: '@OwlAdmin/shared/crud/common/content/form/sections.html.twig'
                priority: 0

        'owl_admin.common.modal.create.content.body.form.content.sections':
            general:
                template: '@OwlAdmin/shared/crud/common/content/form/sections/general.html.twig'
                priority: 0

        'owl_admin.common.modal.create.content.body.form.content.sections.general':
            default:
                template: '@OwlAdmin/shared/crud/common/content/form/sections/general/default.html.twig'
                priority: 0

        'owl_admin.common.modal.create.content.actions':
            cancel:
                template: '@OwlAdmin/shared/crud/common/modal/content/actions/cancel.html.twig'
                priority: 100
            save:
                template: '@OwlAdmin/shared/crud/common/modal/content/actions/save.html.twig'
                priority: 0