sylius_twig_hooks:
    hooks:
        'owl_admin.common.modal.create':
            content:
                template: '@OwlAdmin/shared/crud/common/modal/content.html.twig'
                configuration:
                    stimulus:
                        controllers: {
                            form: {}
                        }
                priority: 0

        'owl_admin.common.modal.create.content':
            header:
                template: '@OwlAdmin/shared/crud/common/modal/content/header.html.twig'
                priority: 300
            body:
                template: '@OwlAdmin/shared/crud/common/modal/content/body.html.twig'
                configuration:
                    page_body_attributes:
                        'data-form-target': 'content'
                priority: 200
            actions:
                template: '@OwlAdmin/shared/crud/common/modal/content/actions.html.twig'
                priority: 100

        'owl_admin.common.modal.create.content.header':
            title_block:
                template: '@OwlAdmin/shared/crud/common/modal/content/header/title_block.html.twig'
                priority: 100
            button_close:
                template: '@OwlAdmin/shared/crud/common/modal/content/header/button_close.html.twig'
                configuration:
                    attributes:
                        'data-form-target': 'action'
                priority: 0

        'owl_admin.common.modal.create.content.header.title_block':
            title:
                template: '@OwlAdmin/shared/crud/common/modal/create/content/header/title_block/title.html.twig'
                priority: 0

        'owl_admin.common.modal.create.content.body':
            form:
                template: '@OwlAdmin/shared/crud/common/modal/content/body/form.html.twig'
                configuration:
                    method: 'POST'
                    render_rest: true
                priority: 0

        'owl_admin.common.modal.create.content.body.form':
            sections:
                template: '@OwlAdmin/shared/crud/common/modal/content/body/form/sections.html.twig'
                priority: 0

        'owl_admin.common.modal.create.content.body.form.sections':
            general:
                template: '@OwlAdmin/shared/crud/common/modal/content/body/form/sections/general.html.twig'
                priority: 0

        'owl_admin.common.modal.create.content.body.form.sections.general':
            default:
                template: '@OwlAdmin/shared/crud/common/modal/content/body/form/sections/general/default.html.twig'
                priority: 0

        'owl_admin.common.modal.create.content.actions':
            cancel:
                template: '@OwlAdmin/shared/crud/common/modal/content/actions/cancel.html.twig'
                configuration:
                    button:
                        attributes:
                            'data-form-target': 'action'
                priority: 100
            save:
                template: '@OwlAdmin/shared/crud/common/modal/content/actions/create.html.twig'
                configuration:
                    method: 'POST'
                    params:
                        save_action: 'referer'
                priority: 0