sylius_twig_hooks:
    hooks:
        'owl_admin.common.modal.update':
            content:
                template: '@OwlAdmin/shared/crud/common/modal/content.html.twig'
                configuration:
                    stimulus:
                        controllers: {
                            form: {}
                        }
                priority: 0

        'owl_admin.common.modal.update.content':
            header:
                template: '@OwlAdmin/shared/crud/common/modal/content/header.html.twig'
                priority: 300
            body:
                template: '@OwlAdmin/shared/crud/common/modal/content/body.html.twig'
                priority: 200
            actions:
                template: '@OwlAdmin/shared/crud/common/modal/content/actions.html.twig'
                priority: 100

        'owl_admin.common.modal.update.content.header':
            title_block:
                template: '@OwlAdmin/shared/crud/common/modal/content/header/title_block.html.twig'
                priority: 0
            button_close:
                template: '@OwlAdmin/shared/crud/common/modal/content/header/button_close.html.twig'
                priority: 0

        'owl_admin.common.modal.update.content.header.title_block':
            title:
                template: '@OwlAdmin/shared/crud/common/modal/update/content/header/title_block/title.html.twig'
                priority: 0

        'owl_admin.common.modal.update.content.body':
            form:
                template: '@OwlAdmin/shared/crud/common/modal/content/body/form.html.twig'
                configuration:
                    method: 'PUT'
                    render_rest: true
                priority: 0

        'owl_admin.common.modal.update.content.body.form.sections':
            general:
                template: '@OwlAdmin/shared/crud/common/modal/content/body/form/sections/general.html.twig'
                priority: 0

        'owl_admin.common.modal.update.content.body.form.sections.general':
            default:
                template: '@OwlAdmin/shared/crud/common/modal/content/body/form/sections/general/default.html.twig'
                priority: 0

        'owl_admin.common.modal.update.content.actions':
            cancel:
                template: '@OwlAdmin/shared/crud/common/modal/content/actions/cancel.html.twig'
                priority: 100
            save:
                template: '@OwlAdmin/shared/crud/common/modal/content/actions/update.html.twig'
                configuration:
                    method: 'PUT'
                    params:
                        save_action: 'referer'
                priority: 0