jms_serializer:
    metadata:
        directories:
            owl-invoice:
                namespace_prefix: "Owl\\Component\\Invoice"
                path: "@OwlInvoiceBundle/Resources/config/serializer"
